
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 36
#define YY_END_OF_BUFFER 37
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[409] =
    {   0,
        0,    0,   37,   36,    1,    2,   35,   27,   28,   29,
       25,   24,   36,    5,   34,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   32,   33,   23,
       23,   23,   23,   23,   23,   23,   30,   31,   36,   36,
       36,    1,   35,   27,   28,   29,   25,   24,   36,    5,
       34,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   32,   33,   23,   23,   23,   23,   23,
       23,   23,   30,   31,   36,   36,    0,    4,    5,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,

       23,   23,   23,   23,   26,    0,    0,    0,    0,    0,
        0,    0,    0,    4,    5,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       26,    0,    0,    0,    4,    4,   23,   23,   23,   23,
       23,   23,   23,   11,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,    0,
        0,    0,    0,    0,    0,    0,    0,    4,    4,    4,
       23,   23,   23,   23,   23,   23,   23,   11,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,

       23,   23,   23,    0,    3,   23,   23,   23,   23,   23,
        0,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       21,   23,   23,   23,   22,    0,    0,    3,    0,    0,
        0,    0,    4,    4,    4,    4,   23,   23,   23,   23,
       23,    0,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   21,   23,   23,   23,   22,    0,   23,   23,   23,
       23,   23,    0,   23,    9,    8,   23,   23,   23,   23,
       23,    0,    0,    0,    0,    0,    0,    4,    4,    4,
        4,   23,   23,   23,   23,   23,    0,   23,    9,    8,
       23,   23,   23,   23,   23,    0,   23,    6,   23,   23,

       23,    0,   23,   23,   23,   23,   23,   23,    0,    0,
        0,    0,    4,   23,    6,   23,   23,   23,    0,   23,
       23,   23,   23,   23,   23,    0,   10,   14,   23,   18,
        0,   20,   23,   15,    0,   23,   23,   23,    0,    0,
        0,    0,    4,   10,   14,   23,   18,    0,   20,   23,
       15,    0,   23,   23,   23,    0,   23,   18,   19,   15,
       23,   23,   16,    0,    0,    0,    0,    0,    0,    4,
        4,   23,   18,   19,   15,   23,   23,   16,    0,   13,
        7,   23,    0,   12,   12,    0,    0,    4,    4,   13,
        7,   23,    0,   23,   13,    0,    0,    4,    4,   23,

       13,   17,   12,   12,    4,    4,   17,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    5,    6,    1,    1,    7,
        8,    9,    1,   10,    1,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    1,    1,    1,
       14,    1,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   18,   25,   26,   27,   28,   29,
       18,   30,   31,   32,   33,   18,   18,   18,   18,   18,
       34,    1,   35,    1,    1,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   46,   52,   53,   54,   55,   56,   46,   46,
       46,   46,   57,    1,   58,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   59,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   60,   61,
        1,    1,    1,    1,    1,   62,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   63,   64,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[419] =
    {   0,
        0,   64, 1148, 1149, 1149, 1149, 1149, 1149, 1149, 1149,
     1149, 1149,  120, 1134, 1149,    0,  102,  114,  102,  115,
      120,  110, 1117,  115,  110, 1118,  122, 1149, 1149,  116,
     1092,  109, 1093,   99,  148,  107, 1149, 1149, 1080,  109,
     1130, 1129, 1128, 1127, 1126, 1124, 1118,  146,  162,  166,
     1115,  198,  262,  161,  164,  194,  201,  191,  192,  202,
      198,  168,  258, 1109, 1103, 1064,  195,  251,  200,  256,
      264,  267, 1095, 1093,  173,  126, 1093, 1088, 1086,    0,
      198,  213,  245,  239,  261,  258,  279, 1076,  288,  289,
      303, 1075,  310,  296,  142, 1049, 1035, 1047, 1043, 1045,

     1040,  297, 1029, 1041, 1149,  302, 1062,  330,  270,  213,
      282,  138,  331,  332,  170,  307,  327,  317,  328,  334,
      336,  338,  359,  344,  368,  352,  375,  370,  388,  380,
      379,  378,  318,  371,  389,  395,  399,  412,  396,  403,
     1052,  421, 1028, 1000,    0,  997,  359,  420,  418,  424,
      433,  422,  435,    0,  430,  438,  443,  429,  434,  454,
      843,  808,  784,  737,  665,  649,  624,  574,  561,  455,
      453,  467,  440,  444,  484,  487,  491,  561,  460,  492,
      479,  484,  481,  491,  497,  495,  512,  480,  516,  518,
      531,  523,  524,  535,  529,  536,  530,  539,  542,  482,

      548,  554,  556,  582, 1149,  562,  570,  473,  568,  568,
      460,  583,  584,  586,  574,  587,  596,  587,  581,  437,
        0,  364,  351,  352,    0,  592,  513,  326,  616,  630,
      635,  639,  527,  603,  605,  609,  612,  624,  632,  637,
      635,  129,  651,  656,  664,  645,  653,  679,  652,  677,
      670,  619,  682,  684,  685,  688,  700,  624,  699,  686,
      690,  694,  694,  695,    0,    0,  711,  704,  710,  717,
      719,  714,  321,  744,  751,  765,  766,  745,  759,  741,
      746,  745,  759,  751,  761,  763,  770,  770,  721,  754,
      777,  762,  791,  798,  800,  799,  770,    0,  799,  813,

      814,  804,  805,  803,  819,  818,  812,  817,  815,  786,
      850,  861,  650,  819,  827,  848,  854,  856,  851,  857,
      858,  871,  884,  886,  852,  899,    0,    0,  860,    0,
      878,    0,  886,    0,  594,  894,  889,  895,  905,  877,
      878,  922,  278,  899,  904,  915,  909,  936,  912,  923,
      918,  912,  932,  930,  936,  955,  926, 1149,    0, 1149,
      948,  954,    0,  944,  939,  973,  989,  982,  993,  976,
      990,  961,  274,  975,  271,  978,  995,  979,  997,    0,
        0,  984,  990,  269, 1028, 1037, 1040, 1005, 1013, 1004,
     1008, 1029, 1042, 1028, 1149, 1056, 1066, 1044, 1050, 1055,

      227,    0, 1067, 1098,  225, 1055, 1034, 1149,  191, 1109,
     1112, 1115, 1118, 1121, 1124, 1127, 1130, 1133
    } ;

static yyconst flex_int16_t yy_def[419] =
    {   0,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  408,  408,  409,
      409,  409,  409,  409,  409,  409,  408,  408,  408,  408,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  411,  411,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,  410,  410,   53,   53,   53,   53,   53,
       53,   53,  410,  410,  410,  410,  412,  413,  408,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,

      409,  409,  409,  409,  408,  408,  410,  410,  410,  410,
      410,  410,  414,  415,  410,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
      410,  410,  412,  408,  413,  413,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  408,
      410,  410,  410,  410,  414,  410,  414,  415,  415,  415,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,

       53,   53,   53,  410,  408,  409,  409,  409,  409,  409,
      408,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  408,  410,  410,  414,  414,
      414,  414,  415,  415,  415,  415,   53,   53,   53,   53,
       53,  410,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,  410,  409,  409,  409,
      409,  409,  408,  409,  409,  409,  409,  409,  409,  409,
      409,  408,  416,  414,  414,  414,  414,  415,  415,  415,
      415,   53,   53,   53,   53,   53,  410,   53,   53,   53,
       53,   53,   53,   53,   53,  410,  409,  409,  409,  409,

      409,  408,  409,  409,  409,  409,  409,  409,  408,  410,
      410,  414,  415,   53,   53,   53,   53,   53,  410,   53,
       53,   53,   53,   53,   53,  410,  409,  409,  409,  409,
      408,  409,  409,  409,  408,  409,  409,  409,  408,  410,
      410,  417,  418,   53,   53,   53,   53,  410,   53,   53,
       53,  410,   53,   53,   53,  410,  409,  408,  409,  408,
      409,  409,  409,  408,  410,  410,  414,  410,  414,  415,
      415,   53,  410,   53,  410,   53,   53,   53,  410,  409,
      409,  409,  408,  410,  410,  414,  414,  415,  415,   53,
       53,   53,  410,  409,  408,  414,  414,  415,  415,   53,

      410,  409,  414,  414,  415,  415,   53,    0,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408
    } ;

static yyconst flex_int16_t yy_nxt[1214] =
    {   0,
        4,    5,    6,    7,    4,    8,    9,   10,    4,   11,
       12,   13,   14,   15,   16,   17,   18,   16,   19,   20,
       16,   21,   22,   23,   24,   16,   16,   25,   26,   27,
       16,   16,   16,   28,   29,   16,   30,   18,   16,   19,
       20,   31,   21,   22,   32,   16,   24,   16,   33,   25,
       34,   35,   16,   16,   16,   36,   37,   38,    4,    4,
        4,    4,   39,   40,   41,   42,    6,   43,   41,   44,
       45,   46,   41,   47,   48,   49,   50,   51,   52,   53,
       54,   52,   55,   56,   52,   57,   58,   59,   60,   52,
       52,   61,   62,   63,   52,   52,   52,   64,   65,   52,

       66,   54,   52,   55,   56,   67,   57,   58,   68,   52,
       60,   52,   69,   61,   70,   71,   52,   52,   52,   72,
       73,   74,   41,   41,   41,   41,   75,   76,   77,   81,
       84,   78,   82,   85,   86,   87,  108,   89,   91,  108,
       93,   83,   90,   81,   97,  100,  103,  101,  108,   94,
      104,   81,   84,   82,   85,   86,  108,   87,   89,   98,
       91,   93,   95,   83,   90,   81,   93,  106,  106,  109,
      113,   94,  108,  114,  110,   94,  108,  161,  115,  118,
      108,  162,  115,  108,  142,  142,  174,   93,  119,  287,
      111,  116,  120,   80,  128,  116,  112,  102,  107,  107,

      118,  107,  107,  107,  107,  107,  107,  107,  108,  107,
      119,  107,  121,  116,  120,  122,  123,  116,  116,  116,
      124,  116,  116,  108,  125,  116,  127,  116,  116,  126,
      147,  107,  107,  121,  141,  179,  122,  108,  123,  172,
      116,  116,  148,  116,  116,  125,  132,  116,  127,  135,
      116,  126,  147,  150,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  148,  107,  107,  107,  107,  107,
      107,  107,  108,  107,  150,  107,  129,  149,  116,  108,
      108,  108,  129,  116,  108,  130,  133,  151,  371,  117,
      152,  130,  108,  153,  116,  107,  107,  129,  171,  149,

      116,  134,  136,  129,  137,  116,  139,  130,  155,  151,
      140,  117,  152,  138,  153,  156,  116,  157,  107,  107,
      107,  107,  107,  107,  107,  107,  158,  160,  160,  155,
      170,  311,  173,  143,  116,  159,  108,  156,  157,  176,
      108,  177,  179,  180,  116,  116,  182,  158,  184,  160,
      160,  167,  170,  109,  116,  116,  116,  159,  110,  181,
      183,  116,  185,  116,  188,  116,  116,  116,  182,  184,
      186,  116,  198,  187,  111,  206,  116,  116,  190,  116,
      112,  181,  183,  116,  185,  116,  116,  116,  189,  191,
      188,  221,  186,  116,  187,  116,  206,  116,  116,  225,

      190,  116,  116,  221,  192,  116,  116,  116,  116,  189,
      191,  194,  188,  193,  195,  116,  116,  116,  196,  116,
      116,  197,  116,  116,  116,  192,  116,  116,  116,  116,
      116,  108,  199,  194,  200,  193,  207,  116,  116,  116,
      188,  203,  208,  194,  116,  116,  209,  202,  116,  204,
      108,  210,  116,  212,  108,  213,  214,  207,  215,  216,
      217,  116,  218,  108,  208,  194,  201,  209,  219,  226,
      179,  204,  210,  227,  221,  212,  213,  108,  214,  215,
      216,  227,  217,  233,  218,  227,  143,  227,  234,  219,
      226,  260,  176,  143,  177,  237,  211,  108,  228,  176,

      238,  177,  179,  180,  235,  239,  116,  116,  116,  116,
      236,  116,  260,  240,  229,  241,  237,  273,  116,  230,
      263,  238,  116,  108,  116,  254,  243,  239,  116,  116,
      116,  116,  244,  116,  240,  231,  241,  179,  246,  116,
      116,  232,  245,  116,  116,  116,  116,  247,  243,  250,
      116,  116,  249,  244,  248,  278,  116,  116,  116,  246,
      242,  116,  116,  116,  245,  116,  116,  116,  247,  116,
      250,  179,  116,  116,  249,  116,  248,  251,  116,  116,
      116,  116,  252,  116,  116,  116,  258,  253,  116,  255,
      252,  116,  108,  252,  259,  256,  257,  116,  261,  262,

      225,  264,  265,  116,  266,  116,  267,  252,  258,  268,
      269,  270,  271,  179,  272,  179,  259,  257,  143,  179,
      261,  262,  264,  265,  176,  266,  177,  221,  267,  279,
      268,  269,  143,  270,  271,  272,  282,  143,  176,  116,
      177,  143,  297,  176,  274,  177,  116,  176,  283,  177,
      284,  116,  360,  360,  343,  280,  275,  281,  282,  116,
      179,  116,  116,  297,  116,  224,  286,  285,  116,  288,
      283,  284,  116,  116,  289,  292,  294,  291,  116,  116,
      116,  116,  290,  116,  116,  276,  116,  277,  286,  285,
      288,  116,  223,  293,  116,  289,  292,  116,  294,  291,

      116,  116,  116,  290,  116,  116,  116,  252,  295,  116,
      108,  116,  116,  116,  293,  116,  221,  298,  299,  116,
      300,  252,  296,  301,  252,  302,  116,  303,  116,  304,
      295,  116,  256,  116,  116,  305,  306,  116,  298,  307,
      299,  308,  300,  296,  309,  301,  143,  302,  116,  303,
      304,  179,  176,  143,  177,  179,  179,  305,  306,  176,
      307,  177,  308,  314,  312,  313,  309,  143,  143,  179,
      116,  312,  116,  176,  176,  177,  177,  315,  116,  313,
      108,  116,  313,  316,  314,  222,  116,  313,  116,  116,
      116,  317,  318,  322,  116,  321,  108,  116,  315,  327,

      116,  319,  320,  116,  116,  316,  312,  312,  116,  108,
      116,  116,  116,  317,  318,  322,  321,  323,  116,  116,
      324,  327,  325,  319,  320,  116,  116,  116,  328,  326,
      340,  329,  330,  331,  332,  333,  221,  334,  336,  323,
      116,  324,  337,  325,  338,  339,  116,  116,  344,  116,
      328,  326,  329,  330,  116,  331,  332,  333,  334,  336,
      108,  108,  221,  143,  337,  342,  338,  339,  116,  176,
      344,  177,  346,  109,  347,  116,  116,  345,  110,  355,
      348,  116,  335,  116,  116,  116,  349,  108,  108,  351,
      350,  220,  357,  346,  341,  347,  358,  116,  116,  345,

      112,  355,  348,  116,  353,  116,  116,  116,  349,  108,
      351,  116,  350,  116,  357,  359,  354,  358,  361,  362,
      116,  363,  108,  364,  143,  353,  116,  365,  366,  356,
      368,  116,  369,  116,  352,  116,  116,  359,  354,  116,
      361,  362,  116,  363,  364,  116,  108,  372,  116,  108,
      116,  356,  374,  116,  373,  380,  376,  116,  116,  116,
      377,  116,  378,  116,  116,  108,  381,  116,  382,  372,
      375,  375,  116,  379,  374,  373,  383,  380,  376,  116,
      384,  116,  377,  108,  378,  116,  179,  381,  116,  382,
      390,  143,  108,  228,  379,  143,  391,  176,  383,  177,

      179,  176,  116,  177,  394,  116,  116,  108,  146,  392,
      116,  205,  390,  233,  385,  179,  229,  391,  234,  395,
      388,  230,  116,  179,  116,  394,  340,  116,  116,  393,
      392,  116,  273,  386,  389,  116,  144,  387,  108,  143,
      236,  395,  143,  232,  116,  176,  402,  177,  176,  400,
      177,  393,  108,  116,  179,  398,  116,  116,  143,  343,
      179,  116,  108,  399,  176,  179,  177,  402,  143,  143,
      400,  401,  108,  407,  176,  176,  177,  177,  116,  169,
      168,  154,  116,  116,  166,  405,  165,  396,  154,  164,
      397,  406,  163,  401,  407,  154,  154,  403,   79,  146,

      143,  144,  342,  108,  116,  108,  176,  404,  177,  107,
      131,  107,  116,  108,  116,  143,  143,  143,  145,  108,
      145,  175,  175,  175,  178,  108,  178,  310,  108,  310,
      367,  367,  367,  370,  108,  370,  108,  108,  108,  108,
      108,  105,   99,   96,   92,   88,   79,  408,    3,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408
    } ;

static yyconst flex_int16_t yy_chk[1214] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,   13,   17,
       19,   13,   18,   20,   21,   22,   76,   24,   25,  242,
       27,   18,   24,   30,   32,   34,   36,   34,  112,   27,
       36,   17,   19,   18,   20,   21,   48,   22,   24,   32,
       25,   27,   30,   18,   24,   30,   35,   40,   40,   48,
       49,   27,   49,   49,   48,   35,   50,   95,   50,   54,
      115,   95,  115,   75,   76,   76,  112,   35,   54,  242,
       48,   55,   55,  409,   62,   62,   48,   35,   52,   52,

       54,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       54,   52,   56,   55,   55,   57,   58,   62,   58,   59,
       59,   56,   67,  110,   60,   61,   61,   69,   57,   60,
       81,   52,   52,   56,   75,  405,   57,  401,   58,  110,
       58,   59,   82,   56,   67,   60,   67,   61,   61,   69,
       57,   60,   81,   84,   52,   52,   52,   52,   52,   52,
       52,   52,   53,   53,   82,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   84,   53,   63,   83,   68,  384,
      109,  375,   71,   70,  373,   63,   68,   85,  343,   53,
       86,   71,  111,   87,   72,   53,   53,   63,  109,   83,

       68,   68,   70,   71,   70,   70,   72,   63,   89,   85,
       72,   53,   86,   71,   87,   90,   72,   91,   53,   53,
       53,   53,   53,   53,   53,   53,   93,   94,  102,   89,
      106,  273,  111,  113,  116,   93,  228,   90,   91,  113,
      108,  113,  114,  114,  118,  133,  118,   93,  120,   94,
      102,  102,  106,  108,  117,  119,  116,   93,  108,  117,
      119,  120,  121,  121,  124,  122,  118,  133,  118,  120,
      122,  124,  133,  123,  108,  147,  117,  119,  126,  126,
      108,  117,  119,  120,  121,  121,  123,  122,  125,  127,
      128,  224,  122,  124,  123,  125,  147,  128,  134,  223,

      126,  126,  127,  222,  129,  132,  131,  130,  123,  125,
      127,  130,  134,  129,  131,  129,  135,  125,  131,  128,
      134,  132,  136,  139,  127,  129,  137,  132,  131,  130,
      140,  142,  135,  130,  136,  129,  148,  129,  135,  138,
      137,  140,  149,  138,  136,  139,  150,  139,  137,  142,
      173,  151,  140,  152,  174,  153,  155,  148,  156,  157,
      158,  138,  159,  171,  149,  138,  138,  150,  160,  170,
      179,  142,  151,  171,  220,  152,  153,  172,  155,  156,
      157,  173,  158,  179,  159,  174,  175,  172,  179,  160,
      170,  208,  175,  177,  175,  181,  151,  176,  176,  177,

      182,  177,  180,  180,  179,  183,  181,  188,  183,  200,
      179,  182,  208,  184,  177,  185,  181,  227,  184,  177,
      211,  182,  186,  227,  185,  200,  186,  183,  181,  188,
      183,  200,  187,  182,  184,  177,  185,  233,  190,  187,
      184,  177,  189,  189,  186,  190,  185,  191,  186,  194,
      192,  193,  193,  187,  192,  233,  195,  197,  191,  190,
      185,  187,  194,  196,  189,  189,  198,  190,  191,  199,
      194,  178,  192,  193,  193,  201,  192,  195,  195,  197,
      191,  202,  197,  203,  194,  196,  206,  198,  198,  201,
      196,  199,  204,  199,  207,  203,  204,  201,  209,  210,

      169,  212,  213,  202,  214,  203,  215,  202,  206,  216,
      217,  218,  219,  234,  226,  235,  207,  204,  229,  236,
      209,  210,  212,  213,  229,  214,  229,  168,  215,  234,
      216,  217,  230,  218,  219,  226,  237,  231,  230,  237,
      230,  232,  258,  231,  229,  231,  252,  232,  238,  232,
      239,  238,  335,  335,  313,  235,  230,  236,  237,  239,
      313,  237,  241,  258,  240,  167,  241,  240,  252,  243,
      238,  239,  246,  238,  244,  247,  249,  246,  243,  249,
      247,  239,  245,  244,  241,  231,  240,  232,  241,  240,
      243,  245,  166,  248,  246,  244,  247,  251,  249,  246,

      243,  249,  247,  245,  250,  244,  248,  251,  250,  253,
      257,  254,  255,  245,  248,  256,  165,  259,  260,  251,
      261,  253,  257,  262,  255,  263,  250,  264,  248,  267,
      250,  253,  254,  254,  255,  268,  269,  256,  259,  270,
      260,  271,  261,  257,  272,  262,  274,  263,  289,  264,
      267,  280,  274,  275,  274,  278,  281,  268,  269,  275,
      270,  275,  271,  282,  274,  278,  272,  276,  277,  279,
      289,  275,  282,  276,  277,  276,  277,  283,  284,  279,
      287,  290,  280,  284,  282,  164,  283,  281,  285,  292,
      286,  285,  286,  292,  282,  291,  310,  288,  283,  297,

      284,  287,  288,  290,  291,  284,  276,  277,  283,  296,
      285,  292,  286,  285,  286,  292,  291,  293,  293,  288,
      294,  297,  295,  287,  288,  294,  291,  295,  299,  296,
      310,  300,  301,  302,  303,  304,  163,  305,  306,  293,
      293,  294,  307,  295,  308,  309,  314,  294,  314,  295,
      299,  296,  300,  301,  315,  302,  303,  304,  305,  306,
      311,  319,  162,  312,  307,  312,  308,  309,  314,  312,
      314,  312,  317,  311,  318,  316,  315,  316,  311,  325,
      319,  317,  305,  318,  320,  321,  320,  340,  341,  322,
      321,  161,  329,  317,  311,  318,  331,  316,  322,  316,

      311,  325,  319,  317,  323,  318,  320,  321,  320,  326,
      322,  323,  321,  324,  329,  333,  324,  331,  336,  337,
      322,  338,  352,  339,  342,  323,  344,  340,  341,  326,
      342,  345,  342,  323,  322,  324,  347,  333,  324,  349,
      336,  337,  346,  338,  339,  351,  348,  346,  344,  365,
      350,  326,  350,  345,  348,  357,  353,  354,  347,  353,
      354,  349,  355,  355,  346,  356,  361,  351,  362,  346,
      352,  352,  350,  356,  350,  348,  364,  357,  353,  354,
      365,  353,  354,  366,  355,  355,  370,  361,  372,  362,
      372,  367,  368,  368,  356,  369,  376,  367,  364,  367,

      371,  369,  374,  369,  382,  376,  378,  379,  146,  377,
      372,  144,  372,  371,  366,  388,  369,  376,  371,  383,
      370,  369,  377,  389,  374,  382,  368,  376,  378,  379,
      377,  390,  385,  367,  371,  391,  143,  369,  385,  386,
      371,  383,  387,  369,  377,  386,  394,  386,  387,  392,
      387,  379,  393,  390,  398,  388,  392,  391,  396,  406,
      399,  407,  141,  389,  396,  406,  396,  394,  397,  403,
      392,  393,  107,  400,  397,  403,  397,  403,  392,  104,
      103,  101,  400,  407,  100,  398,   99,  386,   98,   97,
      387,  399,   96,  393,  400,   92,   88,  396,   79,   78,

      404,   77,  404,   74,  400,   73,  404,  397,  404,  410,
       66,  410,  411,   65,  411,  412,  412,  412,  413,   64,
      413,  414,  414,  414,  415,   51,  415,  416,   47,  416,
      417,  417,  417,  418,   46,  418,   45,   44,   43,   42,
       41,   39,   33,   31,   26,   23,   14,    3,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[37] =
    {   0,
0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "parser.lex"
#line 5 "parser.lex"
#include <iostream>
#include <string>

using namespace std;

extern "C" int yylex(void);

#include "parser.tab.hpp"
#line 892 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 38 "parser.lex"


#line 1083 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 409 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1149 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 40 "parser.lex"
{ /* On ignore */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 42 "parser.lex"
{ cout << "Trouvé un \\n(fin): " << endl; return(FIN_LIGNE);}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 43 "parser.lex"
{ cout << "Trouvé un commentaire multiligne: " << yytext << endl; return(COMMENTAIRE_MULTI); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "parser.lex"
{ cout << "Trouvé un commentaire monoligne: " << yytext << endl; return(COMMENTAIRE_MONO);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "parser.lex"
{
				yylval.valeur_entiere = atoi(yytext);
				cout << "Trouvé un entier: " << yytext << endl;
				return(ENTIER);
		    }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 52 "parser.lex"
{ yylval.texte = strdup(yytext); return(CERCLE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 53 "parser.lex"
{ yylval.texte = strdup(yytext); return(RECTANGLE); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 54 "parser.lex"
{ yylval.texte = strdup(yytext); return(LIGNE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 55 "parser.lex"
{ yylval.texte = strdup(yytext); return(IMAGE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 56 "parser.lex"
{ yylval.texte = strdup(yytext); return(BOUCLER); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 60 "parser.lex"
{ yylval.texte = strdup(yytext); yylval.texte = strdup(yytext); return(EXT_IMG); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 61 "parser.lex"
{ yylval.texte = strdup(yytext); return(PATH); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 64 "parser.lex"
{ cout << "Trouvé une épaisseur: " << yytext << endl; return(EPAISSEUR); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 65 "parser.lex"
{ cout << "Trouvé une couleur: " << yytext << endl; return(COULEUR); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 66 "parser.lex"
{ cout << "Trouvé une opacité: " << yytext << endl; return(OPACITE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 67 "parser.lex"
{ cout << "Trouvé une rotation: " << yytext << endl; return(ROTATION);  }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 68 "parser.lex"
{ cout << "Trouvé un remplissage: " << yytext << endl; return(REMPLISSAGE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 70 "parser.lex"
{ cout << "Trouvé une fenêtre: " << yytext << endl; return(FENETRE); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 71 "parser.lex"
{ cout << "Trouvé une longueur: " << yytext << endl; return(LONGUEUR); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 72 "parser.lex"
{ cout << "Trouvé une hauteur: " << yytext << endl; return(HAUTEUR); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 78 "parser.lex"
{ cout << "Trouvé une couleur: " << yytext << endl; yylval.texte = strdup(yytext); return(COLORNAME);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 79 "parser.lex"
{ cout << "Trouvé un remplissage: " << yytext << endl; yylval.texte = strdup(yytext); return(FILLING);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 81 "parser.lex"
{ cout << "Trouvé un identificateur: " << yytext << endl; yylval.texte = strdup(yytext); return(IDENTIFICATEUR); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 83 "parser.lex"
{ cout << "Trouvé un point: " << yytext << endl; yylval.texte = strdup(yytext); return(DOT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 84 "parser.lex"
{ cout << "Trouvé une virgule: " << yytext << endl; yylval.texte = strdup(yytext); return(VIRGULE); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 85 "parser.lex"
{ cout << "Trouvé un degré: " << "\xc2\xb0" << endl; return(DEGRE); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 86 "parser.lex"
{ cout << "Trouvé un %: " << yytext << endl; return(POURCENT); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 87 "parser.lex"
{ cout << "Trouvé une paranthèse: " << yytext << endl; return(PARENTHESE_OUVRANTE); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 88 "parser.lex"
{ cout << "Trouvé une paranthèse: " << yytext << endl; return(PARENTHESE_FERMANTE); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 89 "parser.lex"
{ cout << "Trouvé une accolade: " << yytext << endl; return(ACCOLADE_OUVRANTE); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 90 "parser.lex"
{ cout << "Trouvé une accolade: " << yytext << endl; return(ACCOLADE_FERMANTE); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 91 "parser.lex"
{ cout << "Trouvé un crochet: " << yytext << endl; return(CROCHET_OUVRANT);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 92 "parser.lex"
{ cout << "Trouvé un crochet: " << yytext << endl; return(CROCHET_FERMANT); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 93 "parser.lex"
{ cout << "Trouvé un égal: " << yytext << endl; return(EGAL); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 94 "parser.lex"
{ cout << "Trouvé un hashtag: " << yytext << endl; yylval.texte = strdup(yytext); return(HASHTAG); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 95 "parser.lex"
ECHO;
	YY_BREAK
#line 1363 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 409 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 409 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 408);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 95 "parser.lex"


